### ISSUE TITLE
CleanUp Environment in Communicaton

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#430] opened 2019-06-12 09:15 UTC
Specialisations of `com::Communication` should override the hooks to [prepare](http://xgm.de/precice/docs/develop/classprecice_1_1com_1_1Communication.html#acbdfdb4af1b16045317231e31e873666) and [cleanup](http://xgm.de/precice/docs/develop/classprecice_1_1com_1_1Communication.html#a22fb3a7602c891fae98864c774d7f431) the environment prior and after establishing the communication.

This involves creating and removing exchange directories.

**Comment by floli** [comment] 2019-06-13 09:01
I am trying to understand the related, now merged PR.

* Why does `BoundM2N::cleanupEstablishment` calls `m2n->prepareEstablishment`?

* `Communication::cleanupEstablishment` is only called on master communication, according to documentation in M2N.hpp? IIRC, first we establish master communication, then the m2n communication. This would mean, that the establish environment is already deleted when the m2n com is to established. The cleanup of the M2N will never be called though

* More questions likely incoming....

**Comment by fsimonis** [comment] 2019-06-14 08:00
> Why does BoundM2N::cleanupEstablishment calls m2n->prepareEstablishment?

That's a bug fixed in 5b32790d

**Comment by floli** [comment] 2019-07-30 07:44
I think we need some more in-code documentation of that. I am very unsure about when it is called and for what kinds of communication on which ranks. See my second question above. I am happy to write some lines of doxygen documentation, as I am probably the best to represent the dumb part here.

**Comment by uekerman** [comment] 2019-07-30 19:35
I think the part which makes all this hard to understand is indeed that we handle the `prepare`/`cleanup` through the master communication. The reason for this is probably the fact that we need to access the exchange directory, which only the communication classes know about. A cleaner solution could be to let `M2N` handle the exchange directory and do the `prepare`/`cleanup` directly in `M2N`. `prepare` then creates the `precice-run` folder (in case there is no folder yet) and `cleanup` removes it (if there is such a folder). Please note that two `M2N`s could have the same but also different exchange directories.

**Comment by fsimonis** [comment] 2019-08-01 09:24
Currently the hooks are called for each preCICE instance in `instance()`.
For each m2n, the hooks are called before establishing the master connection and after connecting the Slaves.

### Example
```
m2n[0] -> prepareEstablishment()
m2n[0] -> connectMasters()
m2n[1] -> prepareEstablishment()
m2n[1] -> connectMasters()

computePartitions()

m2n[0] -> connectSlaves()
m2n[0] -> cleanupEstablishment()
m2n[1] -> connectSlaves()
m2n[1] -> cleanupEstablishment()
```

**Comment by MakisH** [comment] 2019-09-11 09:00
* Summary:
   * The `.address` files are now different and in the `precice-run` directory
   * We always had the problem of remaining address files when a solver crashes in initialization (this is something we cannot fix).
    * **Regression:** Now we keep the address files also in a case where everything runs perfectly. We don't clean-up at the end.
* We need to update the [documentation](https://github.com/precice/precice/wiki/Problems-with-Establishing-the-Communication) (I will do this).
* We need to adapt all the `Allclean` scripts of the tutorials to remove the `precice-run` directory, alongside the `.address` files (reminder: keep the tutorials compatible with many preCICE versions). (we can do this after the release)
* We postpone this to the next release, because it needs quite some refactoring.

**Comment by fsimonis** [comment] 2020-01-14 13:29
After revisiting this issue, I have serious doubts about regarding this feature.

The various ranks on the receiving (thus publishing) side can start and finish in arbitrary order, thus we will never be able to clean-up the environment.

IMHO we should remove `prepareEstablishment` and `cleanupEstablishment` as both functions are broken by design.

**Comment by uekerman** [comment] 2020-01-14 13:59
Not sure if I understand. Every rank can feedback to the master when the connection is established and the master can then clean up once all `M2N`s are established.

**Comment by fsimonis** [comment] 2020-01-15 18:25
I see. But this means that we would have to introduce some sort of barrier solely for the sake of cleaning up files.
Isn't this price justified?

**Comment by uekerman** [comment] 2020-01-16 09:12
We have many such barriers (master waits for all) during the initialization. Should not hurt much.

**Comment by uekerman** [comment] 2020-01-21 17:51
Discussed with @fsimonis:
* Deleting `precice-run` will be very complicated. We would need a barrier over all participants.
* Deleting everything within `precice-run` should however be doable and would be easier if we introduce an additional layer `acceptor-requestor`.

**Closed** 2020-01-31 08:09 UTC
Labels: enhancement, good first issue
