### ISSUE TITLE
BOOST and mingw (msys2)

### ISSUE THREAD

**Issue by 3rav** [precice/precice#94] opened 2018-01-16 08:11 UTC
Hi,
I try to compiled preCICE in mingw, but now I have a problem with boost library.
I install this library by command: pacman -S mingw-w64-x86_64-boost, instalation are OK but name have suffix -mt.

for example:
libboost_log-mt.a
libboost_log_setup-mt.a
libboost_thread-mt.a

When I am compiling preCICE, the compiler reports that there are no boost libraries, how can I correct this?

**Comment by floli** [comment] 2018-01-16 09:38
What is your OS? Windows?

You're using pacman, which is the Arch repository manager, but there is no mingw package in the Arch repo.

**Comment by 3rav** [comment] 2018-01-16 09:47
Hi,
I used Windows 7 with MSYS2 (mingw64):

`rafal@RAV MINGW64 /usr/local/precice-1.0.2
$ pacman -Ss boost
mingw32/mingw-w64-i686-boost 1.66.0-1
    Free peer-reviewed portable C++ source libraries (mingw-w64)
mingw64/mingw-w64-x86_64-boost 1.66.0-1 [zainstalowano]
    Free peer-reviewed portable C++ source libraries (mingw-w64)
`

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-boost

Regards
Rafal

**Comment by floli** [comment] 2018-01-16 09:55
I have little to none experience when it comes to Windows and preCICE is not developed on it.

* Try to symlink the boost libs ```libboost_log-mt.a -> libboost_log.a```.
* Possibly the dynamic linking will fail, because *.a files are for static linking only

**Comment by 3rav** [comment] 2018-01-16 09:59
When changing the manual name (libboost_log-mt.a -> libboost_log.a), then:

`
$ CPLUS_INCLUDE_PATH="/mingw64/include/eigen3" PRECICE_BOOST_ROOT="/mingw64/lib" scons  compiler=g++ petsc=no python=no mpi=no build=release -j4
scons: Reading SConscript files ...

(default)  builddir                  = build      Directory holding build files. ( /path/to/builddir )
(modified) build                     = release    Build type, either release or debug (release|debug)
(default)  compiler                  = g++        Compiler to use.
(modified) mpi                       = False      Enables MPI-based communication and running coupling tests. (yes|no)
(default)  spirit2                   = True       Used for parsing VRML file geometries and checkpointing. (yes|no)
(modified) petsc                     = False      Enable use of the Petsc linear algebra library. (yes|no)
(modified) python                    = False      Used for Python scripted solver actions. (yes|no)
(default)  gprof                     = False      Used in detailed performance analysis. (yes|no)
(default)  platform                  = none       Special configuration for certain platforms (none|supermuc|hazelhen)

Checking whether the C++ compiler works... (cached) yes
Checking for C++ library pthread... (cached) yes
Checking for C++ header file Eigen/Dense... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_unit_test_framework... (cached) yes
Checking for C++ header file boost/vmd/is_empty.hpp... (cached) yes
Checking for C++ header file boost/geometry.hpp... (cached) yes

Targets:   build/release-nopetsc-nompi-nopython/libprecice.a, build/release-nopetsc-nompi-nopython/binprecice.exe, build/release-nopetsc-nompi-nopython/msys-precice.dll, build/release-nopetsc-nompi-nopython/libprecice.dll.a, build/release-nopetsc-nompi-nopython/testprecice.exe, symlink
Buildpath: build/release-nopetsc-nompi-nopython
()
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/release-nopetsc-nompi-nopython/action/ComputeCurvatureAction.o -c -Wall -std=c++11 -fPIC -O3 -DNDEBUG -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc src/action/ComputeCurvatureAction.cpp
g++ -o build/release-nopetsc-nompi-nopython/action/ModifyCoordinatesAction.o -c -Wall -std=c++11 -fPIC -O3 -DNDEBUG -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc src/action/ModifyCoordinatesAction.cpp
g++ -o build/release-nopetsc-nompi-nopython/action/PythonAction.o -c -Wall -std=c++11 -fPIC -O3 -DNDEBUG -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc src/action/PythonAction.cpp
g++ -o build/release-nopetsc-nompi-nopython/action/ScaleByAreaAction.o -c -Wall -std=c++11 -fPIC -O3 -DNDEBUG -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc src/action/ScaleByAreaAction.cpp
In file included from src/utils/assertion.hpp:10:0,
                 from src/mesh/PropertyContainer.hpp:3,
                 from src/mesh/Vertex.hpp:3,
                 from src/action/ScaleByAreaAction.hpp:6,
                 from src/action/ScaleByAreaAction.cpp:1:
src/utils/stacktrace.hpp:3:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h> // for backtrace
          ^~~~~~~~~~~~
compilation terminated.
scons: *** [build/release-nopetsc-nompi-nopython/action/ScaleByAreaAction.o] Error 1
In file included from src/utils/assertion.hpp:10:0,
                 from src/utils/PointerVector.hpp:6,
                 from src/mesh/Group.hpp:4,
                 from src/mesh/Mesh.hpp:3,
                 from src/action/PythonAction.cpp:6:
src/utils/stacktrace.hpp:3:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h> // for backtrace
          ^~~~~~~~~~~~
compilation terminated.
scons: *** [build/release-nopetsc-nompi-nopython/action/PythonAction.o] Error 1
In file included from src/utils/assertion.hpp:10:0,
                 from src/utils/PointerVector.hpp:6,
                 from src/mesh/Group.hpp:4,
                 from src/mesh/Mesh.hpp:3,
                 from src/action/ModifyCoordinatesAction.cpp:3:
src/utils/stacktrace.hpp:3:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h> // for backtrace
          ^~~~~~~~~~~~
compilation terminated.
In file included from src/utils/assertion.hpp:10:0,
                 from src/utils/Globals.hpp:5,
                 from src/action/ComputeCurvatureAction.cpp:2:
src/utils/stacktrace.hpp:3:10: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h> // for backtrace
          ^~~~~~~~~~~~
compilation terminated.
scons: *** [build/release-nopetsc-nompi-nopython/action/ModifyCoordinatesAction.o] Error 1
scons: *** [build/release-nopetsc-nompi-nopython/action/ComputeCurvatureAction.o] Error 1
scons: building terminated because of errors.
`

**Comment by 3rav** [comment] 2018-01-17 08:44
Hi 
I found something like that

[https://stackoverflow.com/questions/28680323/the-execinfo-h-header-file-does-not-exist](url)

Regards
Rafal

**Comment by 3rav** [comment] 2018-01-17 09:00
Hi
I found something like that

https://stackoverflow.com/questions/28680323/the-execinfo-h-header-file-does-not-exist

Regards
Rafal

**Comment by uekerman** [comment] 2018-01-17 17:11
Hi Rafal,

As @floli  said preCICE is currently not targeted towards Windows. A student of mine had it already running some time ago. Thus, in principle it is possible. We might also add proper support for Windows in the mid-future (depending on if we get funding for a project we currently apply for). However, at the moment, we do not have the manpower to also support windows. 

I think you can get rid of your problem above by some small hacks in `src/utils/stacktrace.hpp`. Just remove the linux code (then you don't get a backtrace if preCICE crashes, but that's not that important).  

If in any case, you get in running, please share your hacks with us, e.g. in the [wiki](url). 

Last question: Is there any specific reason why you use Windows? A certain code you want to couple that only runs under Windows?

Benjamin

**Comment by 3rav** [comment] 2018-01-19 13:14
Hi,

Due to the SolidWorks program, which is only available for Windows and most of the work time we using it (CAD model -> FEA -> CAD -> ...).

Regards
Rafal

**Comment by 3rav** [comment] 2018-01-23 14:59
Hi,

I modified ([modified.zip](https://github.com/precice/precice/files/1656424/modified.zip)): SConstruct and stacktrace.hpp, but now first error is:

`LL_DYN_LINK -DPRECICE_NO_SPIRIT2 -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc -I/mingw64/include/eigen3 src/cplscheme/ParallelCouplingScheme.cpp
In file included from E:/msys64/mingw64/include/boost/asio/basic_socket_streambuf.hpp:25:0,
                 from E:/msys64/mingw64/include/boost/asio/basic_socket_iostream.hpp:24,
                 from E:/msys64/mingw64/include/boost/asio.hpp:31,
                 from src/com/SocketCommunication.cpp:5:
E:/msys64/mingw64/include/boost/asio/basic_stream_socket.hpp:49:7: error: redeclared with 1 template parameter
 class basic_stream_socket
       ^
In file included from src/com/SocketCommunication.cpp:1:0:
src/com/SocketCommunication.hpp:23:7: note: previous declaration 'template<class Protocol, class StreamSocketService> class boost::asio::basic_stream_socket' used 2 template parameters
 class basic_stream_socket;
       ^
In file included from E:/msys64/mingw64/include/boost/asio/basic_socket_iostream.hpp:24:0,
                 from E:/msys64/mingw64/include/boost/asio.hpp:31,
                 from src/com/SocketCommunication.cpp:5:
E:/msys64/mingw64/include/boost/asio/basic_socket_streambuf.hpp:210:68: error: wrong number of template arguments (1, should be 2)
   explicit basic_socket_streambuf(basic_stream_socket<protocol_type> s)
`

Regards
Rafal

**Comment by floli** [comment] 2018-01-24 07:42
Which version of preCICE are you using? That should be fixed in https://github.com/precice/precice/commit/a41d9f4c711e9cfafc5ce21ed9062e0563f916af and happens with boost 1.66.

**Comment by 3rav** [comment] 2018-01-24 08:16
Hi,

I apologize for the confusion with the versions, I used the development version before.

Currently the first error is (develop version):

`
src/com/SocketCommunication.cpp: In member function 'virtual void precice::com::SocketCommunication::acceptConnection(const string&, const string&, int, int)':
src/logging/LogMacros.hpp:42:18: error: expression cannot be used as a function
     ERROR(message);                                \
                  ^
src/com/SocketCommunication.cpp:69:3: note: in expansion of macro 'CHECK'
   CHECK(acceptorCommunicatorSize == 1, "Acceptor of socket connection can only have one process!");
   ^
src/com/SocketCommunication.cpp:83:24: error: no match for 'operator<<' (operand types are 'const char [10]' and 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}')
           "Network \"" << _networkName << "\" not found for socket connection!");
                        ^
src/logging/LogMacros.hpp:42:11: note: in definition of macro 'CHECK'
     ERROR(message);  `

**Comment by floli** [comment] 2018-01-24 08:58
Could you give us the compiler used and the exact version?
OS is Win 7, iirc.

**Comment by 3rav** [comment] 2018-01-24 09:11
Win7 with MSYS2 (mingw):

`gcc version 5.4.0 (Rev1, Built by MSYS2 project)`
`GNU ld (GNU Binutils) 2.29.1`

`scons 2.5.1-1`
`mingw-w64-x86_64-eigen3 3.3.3-1`
`mingw-w64-x86_64-boost 1.66.0-1`
`mingw-w64-x86_64-libxml2 2.9.7-1`

More about g++:
`$ g++ -v
Using built-in specs.
COLLECT_GCC=E:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.4.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-5.4.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/5.4.0 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-version-specific-runtime-libs --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 5.4.0 (Rev1, Built by MSYS2 project)
`

**Comment by 3rav** [comment] 2018-02-13 20:32
Hi,
After a few modifications, I was able to get the precice.a file, which then was used to compile ccx for the windows environment (compilation of ccx was successful) but I have error:

`g++ -o build/release-nopetsc-nospirit2-nompi-nopython/action/ScaleByDtAction.os -c -Wall -std=c++11 -lws2_32 -O3 -DNDEBUG -DPRECICE_NO_PETSC -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DBOOST_ASIO_ENABLE_OLD_SERVICES -DPRECICE_NO_SPIRIT2 -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc -I/mingw64/include/eigen3 -I/usr/include/libxml2 -I/mingw64/include/libxml2 src/action/ScaleByDtAction.cpp
build/release-nopetsc-nospirit2-nompi-nopython/com/SocketCommunication.o:SocketCommunication.cpp:(.text+0x312): undefined reference to `__imp_WSAStartup'
build/release-nopetsc-nospirit2-nompi-nopython/com/SocketCommunication.o:SocketCommunication.cpp:(.text+0x5e3): undefined reference to `__imp_WSACleanup'
`

I also had a similar problem with ccx, adding -lws2_32 to Makefile solved the problem, but adding 
-lws2_32 to SConstruct does not solve the precice problem with compilation.

![ccx_precice](https://user-images.githubusercontent.com/24394573/36172027-ef4842fe-1104-11e8-90a7-4e3d7c38a116.png)

File with changes (zip file):
[changes.zip](https://github.com/precice/precice/files/1721589/changes.zip)

**Comment by floli** [comment] 2018-02-14 07:56
Please use triple backticks for code comments, so they are actually readable. I edited most of your comments acoordingly, see https://guides.github.com/features/mastering-markdown/ -> code

**Comment by uekerman** [comment] 2018-02-14 10:18
Maybe it is sufficient to only have the static preCICE lib? You can only build the static lib by `scons staticlib`. Can you build CCX with preCICE already?

**Comment by 3rav** [comment] 2018-02-14 12:45
Hi,

After scons staticlib compiler=g++ petsc=no python=no mpi=no build=release spirit2=no platform=mingw -j6:
```
nompi-nopython/xml/XMLTag.o
ranlib build/release-nopetsc-nospirit2-nompi-nopython/libprecice.a
scons: done building targets.
```

Yes, ccx was built with preCICE (ccx works, drawing in my previous post).

Now I am trying to build SU2 with preCICE, from what I know SU2 requires a dynamic precice library.

**Comment by floli** [comment] 2018-02-14 12:52
We have an experimental build description using CMake, you might want to try that. Checkout the ```cmake``` branch and try ```cmake .```

**Comment by 3rav** [comment] 2018-02-15 09:12
Hi,

I've probably managed to compile preCICE entirely in the mingw environment:

Last folder:
![last](https://user-images.githubusercontent.com/24394573/36248174-dad2cc76-1236-11e8-8839-88e00cb99d89.jpg)

my changes:
a. ImportVRML.hpp, add:
```
 #include <list> 
```
b. LogMacros.hpp, comment:
```
#define CHECK(check, message)                      \
//  if ( !(check) ) {                                \
//    ERROR(message);                                \
  }
```
c. SConstruct, add:
```
vars.Add(EnumVariable('platform', 'Special configuration for certain platforms', "none", allowed_values=('none', 'supermuc', 'hazelhen', 'mingw')))
```

```
elif real_compiler == 'g++':
    env.Append(LIBS = ['libws2_32'])
``` 

```
# ====== Eigen ======
if env["platform"] == "mingw":
    env.Append(CPPPATH = ['/mingw64/include/eigen3'])
checkHeader("Eigen/Dense", "Eigen") 
``` 

```
if env["platform"] == "mingw":
    uniqueCheckLib("boost_log-mt")
    uniqueCheckLib("boost_log_setup-mt")
    uniqueCheckLib("boost_thread-mt")
    uniqueCheckLib("boost_system-mt")
    uniqueCheckLib("boost_filesystem-mt")
    uniqueCheckLib("boost_program_options-mt")
    uniqueCheckLib("boost_unit_test_framework-mt")
else:
    uniqueCheckLib("boost_log")
    uniqueCheckLib("boost_log_setup")
    uniqueCheckLib("boost_thread")
    uniqueCheckLib("boost_system")
    uniqueCheckLib("boost_filesystem")
    uniqueCheckLib("boost_program_options")
    uniqueCheckLib("boost_unit_test_frameworks")
```

```
# ====== LibXML2 ======
env.Append(CPPPATH = ['/usr/include/libxml2'])
env.Append(CPPPATH = ['/mingw64/include/libxml2'])
uniqueCheckLib("xml2")
```

d. SocketCommunication.cpp , comment (every occurrence):
```
//    ERROR(
//        "Accepting connection at " << address);
```

```
 //   ERROR(
 //       "Accepting connection at " << address
 //                                  << " failed: " << e.what());
```

e. stacktrace.hpp

Modified files in the attachment.

[changes_precice.zip](https://github.com/precice/precice/files/1726946/changes_precice.zip)

My questions:
1. Can the filename msys-precice.dll cause problems when compiling SU2?
2. Can the modifications I have made affect the operation of preCICE or the possibility of compiling other programs (SU2, OpenFOAM)?

**Comment by 3rav** [comment] 2018-02-15 13:56
Hello,

Works: CalculiX + SU2 in Windows
![fsi](https://user-images.githubusercontent.com/24394573/36259991-4a20b52e-1260-11e8-8cb2-d7bdbbacda57.jpg)

**Comment by uekerman** [comment] 2018-02-15 15:21
This is great, Rafal! I guess I have to say congratulations as this probably was no trivial task! 
Would you mind sharing more details with us? We would really appreciate if you could document your hacks on a wiki page. We could publish your code then in a branch of preCICE such that others could start from there.

**Comment by 3rav** [comment] 2018-02-20 19:33
In my opinion, it is better to compare files directly (with the program: meld, WinMerge) original and modified. That's why I attach files modified by me.

I've created a wiki page with a preliminary description:
[Wiki pages](https://github.com/precice/precice/wiki/mingw-(Windows-version))

**# Files to compare:**
[precice_changes.zip](https://github.com/precice/precice/files/1741552/precice_changes.zip)

**Comment by uekerman** [comment] 2018-02-25 18:34
Thanks a lot, Rafal! I linked your page from the wiki home. Feel free to edit or add things.
We can close this issue then, right?

**Closed by uekerman** 2018-02-25 18:34 UTC
Labels: building

**Comment by dzw05** [comment] 2019-02-25 04:03
@3rav Great job。I followed this wiki page, and compiled msys-precice.dll. This dynamic lib works successfully  in conjugated heat transfer problem. But when I increased the grids number, precice crashed down. It seems that, the "sockets" method in "m2n" failed.

**Comment by uekerman** [comment] 2019-02-25 08:23
Great to read that the Windows installation is reproducible!
@dzw05 Can you please open a separate issue and document your error with more details? We don't support Windows officially yet, but might be that we still can help you.
