### ISSUE TITLE
Build via Spack fails when using Boost 1.68.0 

### ISSUE THREAD

**Issue by ajaust** [precice/precice#1047] opened 2021-07-27 08:47 UTC
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 20.04_ (linux-ubuntu20.04-haswell)
preCICE Version: 2.2.1
Spack: 0.16.2-3675-cef3a2a6ee

**Describe the problem**

Installing of the Spack spec `precice@2.2.1+python ^boost@1.68.0` fails with errors related to boost. Examples are
```
>> 542    /usr/bin/ld: libprecice.so.2.2.1: undefined reference to `boost::system::detail::system_category_instance'                     
>> 543    /usr/bin/ld: libprecice.so.2.2.1: undefined reference to `boost::system::detail::generic_category_instance'                    
>> 544    collect2: error: ld returned 1 exit status                                                                                      
>> 545    make[2]: *** [CMakeFiles/binprecice.dir/build.make:104: binprecice] Error 1                                                    
546    make[2]: Leaving directory '/data/scratch-ssd1/jaustar/spack-tmp/spack-stage-precice-2.2.1-l6gt3dq4g7r4kj42s7s6ki7dusadp4zi/spa
        ck-build-l6gt3dq'                                                                                                               
>> 547    make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/binprecice.dir/all] Error 2

>> 663    /data/scratch/jaustar/software/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/boost-1.68.0-mnf5ydxdxinl32urgvg6zyhouyunsrl
          b/include/boost/system/error_code.hpp:908: undefined reference to `boost::system::detail::generic_category_instance'
   664    /usr/bin/ld: CMakeFiles/testprecice.dir/src/com/tests/SocketCommunicationTest.cpp.o: in function `boost::system::error_code::er
          ror_code(int, boost::system::error_category const&)':
>> 665    /data/scratch/jaustar/software/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/boost-1.68.0-mnf5ydxdxinl32urgvg6zyhouyunsrl
          b/include/boost/system/error_code.hpp:638: undefined reference to `boost::system::detail::generic_category_instance'
   666    /usr/bin/ld: CMakeFiles/testprecice.dir/src/com/tests/SocketCommunicationTest.cpp.o: in function `boost::system::error_category
          ::std_category::equivalent(std::error_code const&, int) const':
>> 667    /data/scratch/jaustar/software/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/boost-1.68.0-mnf5ydxdxinl32urgvg6zyhouyunsrl
          b/include/boost/system/error_code.hpp:923: undefined reference to `boost::system::detail::generic_category_instance'
   668    /usr/bin/ld: CMakeFiles/testprecice.dir/src/com/tests/SocketCommunicationTest.cpp.o: in function `boost::system::error_category
          ::std_category::equivalent(int, std::error_condition const&) const':
>> 669    /data/scratch/jaustar/software/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/boost-1.68.0-mnf5ydxdxinl32urgvg6zyhouyunsrl
          b/include/boost/system/error_code.hpp:878: undefined reference to `boost::system::detail::generic_category_instance'
   670    /usr/bin/ld: CMakeFiles/testprecice.dir/src/com/tests/SocketCommunicationTest.cpp.o: in function `boost::system::error_conditio
          n::error_condition(int, boost::system::error_category const&)':
>> 671    /data/scratch/jaustar/software/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/boost-1.68.0-mnf5ydxdxinl32urgvg6zyhouyunsrl
          b/include/boost/system/error_code.hpp:528: undefined reference to `boost::system::detail::generic_category_instance'
>> 672    /usr/bin/ld: libprecice.so.2.2.1: undefined reference to `boost::system::detail::system_category_instance'
>> 673    collect2: error: ld returned 1 exit status
>> 674    make[2]: *** [CMakeFiles/testprecice.dir/build.make:1139: testprecice] Error 1
   675    make[2]: Leaving directory '/data/scratch-ssd1/jaustar/spack-tmp/spack-stage-precice-2.2.1-l6gt3dq4g7r4kj42s7s6ki7dusadp4zi/spa
          ck-build-l6gt3dq'
>> 676    make[1]: *** [CMakeFiles/Makefile2:305: CMakeFiles/testprecice.dir/all] Error 2
   677    make[1]: Leaving directory '/data/scratch-ssd1/jaustar/spack-tmp/spack-stage-precice-2.2.1-l6gt3dq4g7r4kj42s7s6ki7dusadp4zi/spa
          ck-build-l6gt3dq'
   678    make: *** [Makefile:166: all] Error 2
```

See the full build output for more infromation:

[spack-build-out.txt](https://github.com/precice/precice/files/6883929/spack-build-out.txt)
[errors.txt](https://github.com/precice/precice/files/6883930/errors.txt)

**Step To Reproduce**
```
spack env create precice-2_1_1-boost_1_68_0
spack env activate -p precice-2_1_1-boost_1_68_0
spack add precice@2.2.1+python ^boost@1.68.0
spack concretize -f
spack install
```

**Expected behaviour**

Spack installs preCICE successfully. 

**Additional context**

The logfiles are attached above.

**Comment by fsimonis** [comment] 2021-07-27 11:17
@ajaust Thanks for reporting this issue.

I did some digging and it looks like this is a know problem of Boost 1.68.0.
https://github.com/boostorg/system/issues/26

Do you have the option to upgrade to 1.69.0 or newer?

**Comment by ajaust** [comment] 2021-07-27 11:54
Yes, I already moved on to a newer Boost and that fixed it for me. I just stumbled on it because some other dependency (not related to preCICE) in my Spack environment pulled in Boost 1.68.0, but I sorted that out as well.

**Comment by fsimonis** [comment] 2021-07-29 09:33
Given that the issue is Boost specific and heavily depends on the system, I am going to close this and add a note in the docs.

**Closed by fsimonis** 2021-07-29 09:33 UTC
Labels: bug
