### ISSUE TITLE
Inconsistent `BoundingBox` implementation

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1418] opened 2022-08-18 08:52 UTC
**Describe the problem**
While working on #1273, I stumbled across our `BoundingBox` class and was not completely sure about several design decisions. There are functions which (seemingly arbitrarily) do nothing without telling the user, in case the bounding box is defined 'empty', e.g.,

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L133-L141

or 

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L143-L157

Interestingly, overloaded versions of these functions don't care about the emptyness of the box

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L123-L131

 or 

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L115-L121

Overall, the definition of empty is also not completely clear to me, shouldn't this be implemented as `GreaterEqual` and not as `Greater` (and also implemented in a one-liner). The documentation in the code reads that 'empty' is the same as default state, which is strictly speaking not the case (and not what the function checks)

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L45-L53

Having said this, the `getArea` function doesn't seem to make sense to me: if we have dead axis, the bounding box is used to be empty in at least one direction, which will fail in debug mode and just return a value in release mode

https://github.com/precice/precice/blob/b51fd77b2bdda66b4942cfbd1c4a6d9d34055c87/src/mesh/BoundingBox.cpp#L95-L103

**Expected behaviour**
More of a place to discuss the points above. In principle: a consistent, well-documented class with tests.

**Comment by fsimonis** [comment] 2022-08-27 05:33
The BoundingBox class is a weird one.

IIRC, many design decisions are based on the old implementation which was simply a vector of min max pairs for each dimension.

Cleaning this class up would be great.

**Comment by oguzziya** [comment] 2022-10-07 21:22
This was a result of one of my initial tasks, so it is on me (shame 🔔). As @fsimonis mentioned, it was based on the old implementation, `_bounds` is simply [x_min, x_max, y_min, y_max, z_min, z_max]. I am not sure how the new implementation looks like.

I think the main problem is the `empty()` function. As you mentioned it does not check emptiness at all, it just checks whether it is in the default state ([std::numeric_limits<max>, std::numeric_limits<min>, ... ]). I am not sure why this was necessary though. So in the end, `empty()` function should have been `isDefault()` actually.

Based on this definition, `expandBy(double value)` and `scaleBy(double value)` should not be called on default state, so instead of simply returning there should have been an assert actually. But again, I do not know why.

For `expandBy(Vertex)` or `expandBy(BoundingBox)` being in default state does not matter and we will just create the BoundingBox around the given object. Therefore, we do not have to check "default"ness.

With the same logic, we should not have a default state `BoundingBox`, so `getArea()` should work fine. 

In the end, the problem is that `empty()` function does not check what its name implies at all. I am not sure how the usage has changed over time but these were the reasoning in general. It has been 2 years since I implemented this so I forgot most of the details but let me know if I can be more help.

**Comment by davidscn** [comment] 2022-11-09 12:10
In my opinion we should replace the raw `bounds` vector by two vertices (representing the corners of the bounding box) and clean-up the remaining functions accordingly. The comparison operators etc are already defined for vertices. @fsimonis any opinion on that?

**Comment by fsimonis** [comment] 2022-11-09 12:18
Totally agree.

We just need to be careful on how to  handle an empty box vs a box containing one point.

**Comment by playcatchup** [comment] 2022-11-10 14:02
Dear preCICE developers,

@jeremiahbintang and I would like to solve this issue. Could anyone guide us to know this issue in-depth?

Thank you in advance.

@MakisH

**Comment by davidscn** [comment] 2022-11-11 07:48
Thanks a lot @playcatchup and @jeremiahbintang,

The reason why this issue is a 'good-first' issue is primarily that you don't need to look into the whole preCICE library, but almost exclusively refactor the [`BoundingBox class`](https://github.com/precice/precice/blob/develop/src/mesh/BoundingBox.hpp). As written in the issue, there are two parts in this issue:

1. the refactoring. [As described above](https://github.com/precice/precice/issues/1418#issuecomment-1308657431), once you replace the [bounds](https://github.com/precice/precice/blob/bee47b164e28e6e5936e9b46de39d81cd64c42fd/src/mesh/BoundingBox.hpp#L101-L102) by two instances of a [`Vertex`](https://github.com/precice/precice/blob/develop/src/mesh/Vertex.hpp) (maybe a pair or an array), all functions within the class need to be adapted accordingly, as most of the functions rely on the `bounds` array. Note that you might need to adapt some function names/signatures in the [unit tests](https://github.com/precice/precice/blob/develop/src/mesh/tests/BoundingBoxTest.cpp) of this class as well in case you change things there.
2. the behavior of the class: we need a clear definition of the default state of a bounding box (see also the [comment above](https://github.com/precice/precice/issues/1418#issuecomment-1272096729)), and a definition of an empty bounding box. Once we have that, we can add checks in the functions in order to disable certain calls when the bounding box is, e.g., empty. Example: Calling `scaleBy` on a default bounding box should probably lead to an error (`PRECICE_ASSERT(isDefault)`), or something similar.

I would recommend to start with step one and see how this works out. I could imagine that step 2 becomes much clearer once you are done with the first step, but in case step two is too intricate, that's not a problem, doing only step 1 would already be of great help. In any case, do not hesitate to ask if anything is unclear.

**Comment by playcatchup** [comment] 2022-11-11 20:01
Thank @davidscn for your explanation and your time! We'll try to spec things out first before execution, and we'll come back to you.

**Comment by playcatchup** [comment] 2022-11-15 12:48
Dear @Davidscn,

good afternoon!

Firstly, we (@jeremiahbintang and I) change the `BoundingBox` constructor to accept two `Vertex` instances rather than `bounds`.  
```
BoundingBox::BoundingBox(Vertex boundMin, Vertex boundMax)
{
  // PRECICE_ASSERT 1
  const int& dimMin= boundMin.getDimensions();
  const int& dimMax= boundMax.getDimensions();
  PRECICE_ASSERT(dimMin==dimMax,"Dimension of min and max vertices should be the same.", dimMin, dimMax);
  
  // PRECICE_ASSERT 2
  const auto& boundMinCoords = boundMin.rawCoords();
  const auto& boundMaxCoords = boundMax.rawCoords();
  bool isMinLessThanMax = true;
  for (int i= 0; i < dimMin; i++) {
    if(boundMinCoords[i] >= boundMaxCoords[i])
    {
      isMinLessThanMax = false;
      break;
    }
  }
  PRECICE_ASSERT(isMinLessThanMax,"Each component of min vertex must be less than that of max vertex in the same axis direction.", boundMinCoords, boundMaxCoords);
 	
  // Assign private members
  _boundMin = std::move(boundMin);
  _boundMax = std::move(boundMax);
  _dimensions = dimMin;
}
```
Moreover, when we look through the code, we found only `dataVector` is dependent to the old implementation of `bounds` (as it returns `_bounds` directly). Now because we replace the parameters by `Vertex`, either we need to make a vector from two `Vertex` instances, or we change the implementation. It's only called by CommunicationBoundingBox.

After the above changes are approved, we will go on modifying all functions within the `BoundingBox` need to be adapted and adapt corresponding function names/signatures of `BoundingBox` for the unit tests.

**Comment by fsimonis** [comment] 2022-11-16 14:28
@playcatchup Working directly with `mesh::Vertex` makes testing a bit of a pain, as one needs to create these things first. Also, they express more information as necessary.

Given that the `BoundingBox` only cares about coordinates, I would prefer to keep the constructor as close to coordinates as possible. You can start accepting `Eigen::VectorXd` as input.
An additional helper or delegating constructor taking `Vertex` could be helpful.

**Comment by playcatchup** [comment] 2022-11-16 21:01
@fsimonis Thanks for your reply and suggestion! We'll follow your advice and create a pull request once we have a update.

**Comment by fsimonis** [comment] 2022-11-18 10:02
You could also use a nx2 `Eigen::Matrix` to get the best of both worlds:
* Easy access and usage of the coordinates
* Everything is stored in a buffer which can easily be sent and received.

**Comment by fsimonis** [comment] 2022-11-21 16:38
You have two options for storing the min max points.
* directly storing them as two members
* storing them as a Matrix

An Eigen::Vector is an Eigen::Matrix with a dimension set to 1.

Thinking about this again, it may get a bit unpleasant to handle a matrix.
Let's ignore the second method until we really need something like that.

So, go ahead with storing the points as individual members. Sorry for the back and forth :)

**Comment by uekerman** [comment] 2022-11-25 10:57
Connected to #1111

**Comment by playcatchup** [comment] 2022-12-01 13:14
According to [the suggestion](https://github.com/precice/precice/issues/1418#issuecomment-1311348029) from @fsimonis, we've (@jeremiahbintang) made a [draft pull request](https://github.com/precice/precice/pull/1495) for the 1st part, and we are moving to the 2nd part of this issue.

In order to fix `empty()` and `isDefault()` of a BoundingBox, we would like to ask the following questions:
1. Could we define the `empty()` as "a BoundingBox has less than two vertices"?
2. Could we define the `isDefault()` as "a BoundingBox have one vertex whose entries having the same value equal to `std::numeric_limits<double>::lowest()` and another one whose entries having the same value equal to `std::numeric_limits<double>::max()`"?

**Closed** 2023-02-10 09:12 UTC
Labels: good first issue
