### ISSUE TITLE
IQN implementation does not handle starting from zero-state

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1496] opened 2022-12-01 09:53 UTC
**Describe your setup**

preCICE Version: v2.5.0

**Describe the problem**

Users starting simulations from a zero/steady state, often face the following error when they apply an IQN acceleration:

https://github.com/precice/precice/blob/e920870a8848e1f4fbf194c6f545c52b88083d2b/src/acceleration/BaseQNAcceleration.cpp#L219-L222

This often leads them to fall back to much slower methods, such as Aitken or even constant under-relaxation. Typically, IQN works just fine in these cases if we don't start from a zero initial state.

This has already affected at least:
- [This user simulating a Fluid-Fluid coupling scenario](https://precice.discourse.group/t/fluid-fluid-coupling/1185/2)
- [This user simulating an FSI scenario](https://precice.discourse.group/t/mapping-issue-in-fsi-simulation/647/6)
- Our ATHLET-preCICE project (starting from zero flow and slowly opening a valve)

**Step To Reproduce**

I have not managed to reproduce this situation with any of our tutorials. I already tried the following:
- Modifying the `flow-over-heated-plate` to use IQN instead of Aitken (see https://github.com/precice/tutorials/issues/313)
- Modifying the `partitioned-pipe` tutorial to start with zero flow and to set stricter convergence measures
- Modifying the `partitioned-heat-conduction` case to use stricter convergence measures. In a currently not publicly available variant of this case where we set the right-hand-side to zero, we can reproduce the issue with relative convergence measures of 1e-9.

@uekerman any further ideas on what could trigger this error?

**Expected behaviour**

In case this situation is encountered, IQN could just ignore the column and keep running, only showing a warning.

**Comment by KyleDavisSA** [comment] 2022-12-06 09:08
With the statement `zero/steady state`, you are referring to something that stays almost constant for multiple iterations/time steps? Having an initial `zero` vector is not a problem, the problem is that the initial `zero` does not change from iteration to iteration. 

Note: This should also only be an issue for parallel-implicit coupling and not serial-implicit coupling.

**Comment by MakisH** [comment] 2022-12-08 12:30
> Note: This should also only be an issue for parallel-implicit coupling and not serial-implicit coupling.

Why is that?

@davidscn has created a variant of the partitioned heat conduction case with a serial-implicit coupling, which suffers from this issue.

**Comment by KyleDavisSA** [comment] 2022-12-09 11:28
Ah, sorry, I misunderstood. The main problem is that the difference residual is zero, but perhaps not the residual. I see two scenarios here:

1. The Delta_R is zero, which means we can't add the new column for the IQN method. 
2. The residual is zero, which means that the problem should have converged. 

In scenario 1, we can continue to use IQN if there are already columns in V_k and W_k, but if there are not enough columns, convergence will probably be very bad. What would be worse is if this happens in the beginning when there is maybe only one column in V_k and W_k. In this case, a simple under-relaxation step could be performed in each iteration.

In scenario 2, the new solution would be equal to the old solution and would not change. But the time window should converge, making this a non-issue. 

My solution would be to skip adding the new column and force a simple under-relaxation step when a zero Delta_R column is found.

**Comment by MakisH** [comment] 2022-12-12 21:49
> The problem should be reproducible when changing from parallel to serial coupling for the [direct mesh access tutorial](https://precice.org/tutorials-partitioned-heat-conduction-direct.html).

Converting from `parallel-implicit` to `serial-implicit` and removing the acceleration of `Heat-Flux` indeed reproduces the issue. Thank you!

**Comment by BenjaminRodenberg** [comment] 2023-11-03 07:19
Since @uekerman pointed to this issue from https://github.com/precice/tutorials/issues/385, some comments and questions from my side:

* @MakisH: As far as I understand the main problem here is that we could not really reproduce this issue. Do you think the setup I'm describing in https://github.com/precice/tutorials/issues/385 closes this gap?
* With #1863 @Fujikawas is currently preparing a fix for this bug. We still need some testing here, but having a PR is a good step to agree on the actual problem, how to test it and a possible solution.
* Since I'm running into this issue in my research, I would like to propose doing a bugfix release https://github.com/precice/precice/milestone/21 as soon as we have a fix for this bug. This helps me a lot to have a proper preCICE version to refer to instead of a commit hash with some custom patch. Any opinions, esp. @fsimonis? From my understanding a bugfix release should be simple to do (I never did one, so actually no clue). Backporting this patch to version 2.5.0 should also be fine, if we keep the changes at a minimum.

**Comment by MakisH** [comment] 2023-11-13 21:46
>     * @MakisH: As far as I understand the main problem here is that we could not really reproduce this issue. Do you think the setup I'm describing in [Partitioned heat conduction: Crash, if max-time >= 2.0. Why? tutorials#385](https://github.com/precice/tutorials/issues/385) closes this gap?

Reproducing the problem is not an issue, see above: https://github.com/precice/precice/issues/1496#issuecomment-1347389600

>     * With [Give warning info other than error by zero-update of `V` in QN-update #1863](https://github.com/precice/precice/pull/1863) @Fujikawas is currently preparing a fix for this bug. We still need some testing here, but having a PR is a good step to agree on the actual problem, how to test it and a possible solution.

Having a warning instead of an error is indeed a good step, although it only hides the problem under the carpet.

>     * Since I'm running into this issue in my research, I would like to propose doing a bugfix release https://github.com/precice/precice/milestone/21 as soon as we have a fix for this bug. This helps me a lot to have a proper preCICE version to refer to instead of a commit hash with some custom patch. Any opinions, esp. @fsimonis? From my understanding a bugfix release should be simple to do (I never did one, so actually no clue). Backporting this patch to version 2.5.0 should also be fine, if we keep the changes at a minimum.

The fact that this helps you cite a reference version is enough of a good reason for me to have a bugfix release. And I already know of a few users (see mentions in Discourse) that could benefit from this without having to update everything to v3.

**Comment by MakisH** [comment] 2023-11-28 09:10
#1895 fixed this issue (should be included in the upcoming v3.0.0 and v2.5.1).

**Closed** 2023-11-28 09:10 UTC
Labels: bug
