### ISSUE TITLE
Performance limited by receive buffer capacity (1-way coupling)

### ISSUE THREAD

**Issue by MakisH** [precice/precice#104] opened 2018-02-14 10:06 UTC
Let's assume this scenario: Participant A sends data to Participant B during `advance()` and continues to the next timestep. If Participant B is too slow, then the continuous sending of data will saturate the receive buffer of B. Participant A will then hang until more data can be received.

This problem can be platform-dependent. In order to solve this issue, we need to be able first to find out the size of these buffers. Then we could either configure these buffers to have a different size (if possible), or store the sending data somewhere else before putting them in the system buffers.

In order to reproduce this issue, I use the aste framework (commit [75b800f](https://github.com/precice/aste/commit/75b800f03ecd3f5e1b45a825d481f2f98a684dd3) at the moment), where I added the following lines in the `main.cpp`:

```c++
#include <thread>
#include <chrono>

// ... after advance():

    if (participant == "B") {
        std::this_thread::sleep_for (std::chrono::seconds(999999));
    }
```

and I set the `max-time` in `precice.xml` to a very high number. This way, A keeps sending data, but B never reads them. On my laptop, Participant A paused at the `dt# 4384`, using the default mesh sizes (10x10 elements). I am investigating these further, also in the MAC Cluster and I will update the issue.

**Comment by floli** [comment] 2018-02-14 10:25
> Let's assume this scenario: Participant A sends data to Participant B during advance() and continues to the next timestep. If Participant B is too slow, then the continuous sending of data will saturate the receive buffer of B. Participant A will then hang until more data can be received.

Minor correction imho: A will hang when receive buffer of B is saturated and send buffer of A.

I have just merged my fork into aste, could you branch and commit your changes, s.t. we can also test it using exact the same code and settings.

**Comment by MakisH** [comment] 2018-02-16 00:08
I ran it on the MAC-Cluster (partition `snb`) in the following way:

```
# Allocate two nodes:
# We want 4 MPI processes (tasks) for each participant, so 8 in total. Each node has 32 logical processors (CPUs), so we require 8 CPUs per task (64 CPUs in total = 2 nodes).
salloc --partition=snb --ntasks=8 --cpus-per-task=8

# Run participant A with 4 processes, all in one node, redirect the output to log.A and return
mpiexec.hydra -ppn 4 -n 4 ./aste -p A > log.A 2>&1&

# The same for participant B
mpiexec.hydra -ppn 4 -n 4 ./aste -p B > log.B 2>&1&

# Inspect the log.A
tail -f log.A
```

Every time, it stops at around dt# 480-492, with the default mesh size. If I set `--cpus-per-task=1` (i.e. allow everything in one node), the observed time does not change. I am not completely sure if my configuration indeed runs the participants in different nodes, but I will try to print the hostnames tomorrow.

For this test, I used commit [e7c0c1f](https://github.com/MakisH/aste/commit/e7c0c1f22bdbaad4ebb5af6107d9053a6141d3b8) from my forked aste (I forked because I am not a collaborator in this repository) and preCICE 1.0.2. I changed to nearest-neighbor mapping, as I did not have PETSc.

With the same setup on my laptop, the observed time is around 4290 (9 times higher).

**Comment by MakisH** [comment] 2018-02-20 07:39
I modified aste to print the hostname, so that I can know if the two participants run on different nodes:

```c++
#include <stdlib.h>
// ...
int main(int argc, char *argv[])
{
  system("hostname");

  MPI_Init(&argc, &argv);
  // ...
}
```

I managed to get different nodes by using the `exclusive` option. I also started the two participants from two different ssh terminals.
```
# Terminal 1
# Open connection
ssh -Y mac-login-intel.tum-mac.cos.lrz.de
# Allocate a full and exclusive node
salloc --partition=snb --ntasks=4 --cpus-per-task=8 --exclusive
# Run participant A with 4 processes, all in one node, redirect the output to log.A and return
mpiexec.hydra -ppn 4 -n 4 ./aste -p A > log.A 2>&1&

# Terminal 2: the same for B
```

Note that in this case we need to change the `network` property of the `m2n:sockets` node to `ib0` (from `lo`), so that there can be communication among different nodes. Note also that some times it take a some seconds before the two participants find each other (or at least before the output is shown).

The observed time on which participant A pauses is around 174. The observed time does not change if I use 2 or 8 MPI ranks. Afterwards I ran it for 16 MPI ranks and the time dropped to 168. Then I ran it on the Bulldozer for 4 MPI ranks and I got again 168. I have only run everything 2-3 times, on a small time period. Maybe the network load plays an important role here.

**Comment by floli** [comment] 2018-02-20 08:25
On my local machine (Linux 4.15.3) with 2 ranks each using interface lo it stopped after timestep 4393. precice build was debug, aste build release. Using release build it stopped after 6382.

On SuperMuc (Phase 2, two 2 ranks each, 2 ranks per node, 2 nodes, interface ib0, all builds release.) it ran 1000001 timesteps, but on both ranks (???). Ran it twice, both runs had the exact same numbers (which hasn't happened on my own machine when repeating runs)

Commit was your latest master https://github.com/MakisH/aste/commit/e7c0c1f22bdbaad4ebb5af6107d9053a6141d3b8

BTW, I gave you contributor permission on precice/aste.

SuperMuc job file:
```
#@ wall_clock_limit = 00:10:00
#@ job_type = MPICH
#@ job_name = Makis_ASTE
#@ class = test
#@ island_count = 1
#@ network.MPI = sn_all,not_shared,us
#@ node = 2
#@ tasks_per_node = 2
#@ energy_policy_tag = my_energy_tag
#@ output = $(job_name).$(schedd_host).$(jobid).out
#@ error = $(job_name).$(schedd_host).$(jobid).err
#@ initialdir = .
#@ notification=always
#@ notify_user = xxx
#@ queue

. /etc/profile
. /etc/profile.d/modules.sh

module swap python python/3.5_intel
module load gcc/6

module unload mpi.ibm
module unload mkl
module load mpi.intel

mpirun -n 2 ./aste -p A > log.A &
mpirun -n 2 ./aste -p B > log.B
```

**Comment by floli** [comment] 2018-02-20 09:36
Two ideas:
* A seperate application runs between the network interface and does the buffering. It provides a socket to precice.
* A dummy solver is implemented in precice that sits between FASTEST and Ateles and does the store and forward stuff

**Comment by uekerman** [comment] 2018-02-23 17:43
I had a closer look at the second idea. It would mean we need **two SolverInterfaces** in this dummy solver because we want to advance both interfaces differently. This would be no problem. A bigger problem, however, is that we need a **surface mesh**:
- Can we generate the Ateles surface mesh? Probably possible, but not straight-forward. 
- Or can we can read in the FASTEST surface mesh? 
- Or we use a further mesh. This would introduce another mapping error, but might not be too bad. But still: We have to define the geometry explicitly. 

Once, we have the surface mesh, we need to think about how to partition it. And a final drawback is, of course, that the dummy solver also needs own computational resources. 

The big advantage is that this solution would be nicely separated from preCICE and does not introduce further complexity that nobody else would need.

**Comment by fsimonis** [comment] 2019-11-27 08:07
From my perspective, this behaviour is to be expected.

If the receiving Participant is running slower than the sending Participant, then the buffer on the receiving side will reach its maximum capacity and the sending participant will have to block until it can send more.

This is a problem in load-balancing the participants and not a bug.

**Comment by uekerman** [comment] 2019-11-28 13:32
IIRC this issue was to merely study the behavior. @floli implemented the requested feature as a follow-up of this. So, I close this.

**Closed by uekerman** 2019-11-28 13:32 UTC
Labels: enhancement
