### ISSUE TITLE
Make sure that complete API is supported by bindings

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#520] opened 2019-09-13 07:57 UTC
example for a missing function: `getVersion` #380

# bindings that should be checked

- [x] python refer to https://github.com/precice/python-bindings/issues/16
- [x] MATLAB refer to https://github.com/precice/matlab-bindings/issues/6
- [x] C
- [ ] Fortran90
- [ ] Fortran2003

**Comment by MakisH** [comment] 2020-01-30 22:53
I compared the C++ API with C, Fortran, and the Fortran 2003 module

## C

- Missing custom MPI communicator (see #479)
- `isTimeWindowComplete` has a different name: `precicec_isCouplingTimeWindowComplete`
- Missing `getMeshIDs`

Everything else looks good.

## Fortran

- Missing custom MPI communicator (see #479)

Many functions have different style names and are in a different order than in C, but everything looks good.

## Fortran 2003 module

I did not go into details, but looks the same as Fortran.

So, this is a duplicate of #479.

**Comment by IshaanDesai** [comment] 2020-04-27 09:02
There is a name inconsistency in the Fortran bindings (withint the preCICE Repo and not the external module) when compared to the C++ API:
* The function `isActionRequired` in the C++ API is `precicef_action_required` in the Fortran bindings in [this line](https://github.com/precice/precice/blob/develop/extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp#L170). The consistent name would be `precicef_is_action_required`.
* The function `isCouplingOngoing` in the C++ API is `precicef_ongoing` in the Fortran bindings in [this line](https://github.com/precice/precice/blob/develop/extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp#L98). The consistent name would be `precicef_is_coupling_ongoing`.

**Comment by MakisH** [comment] 2020-07-19 08:34
This is now only a duplicate of #479, which is more complicated. Let's close this and address any other inconsistencies in separate issues, in the respective repositories.

**Closed by MakisH** 2020-07-19 08:34 UTC
Labels: good first issue
