### ISSUE TITLE
Missing error message for invalid acceleration data vectors in serial coupling scheme

### ISSUE THREAD

**Issue by Alphaoo1** [precice/precice#869] opened 2020-10-01 06:05 UTC
On suggestion of @uekerman  I am opening an issue.

**Background**
I was trying to run the a 2-way FSI simulation (OpenFOAM +CalculiX, the OF adapter is a bit modified for interFoam).
As for preCICE I use v2,1 and CalculiX adapter with CCXv2.16.
This the precice config that I am using. 
[precice-config.xml.txt](https://github.com/precice/precice/files/5309721/precice-config.xml.txt)

I get the following in CalculiX side:
```
 Setting up preCICE participant Calculix, using config file: config.yml
---[precice]  This is preCICE version 2.1.0
---[precice]  Revision info: v2.1.0-2-g42abc38c-dirty
---[precice]  Configuring preCICE with configuration "./precice-config.xml"
---[precice]  I am participant "Calculix"
Set ID Found 
Read data 'Forces0' found with ID # '2'.
Write data 'Displacements0' found with ID # '3'.
---[precice]  Setting up master communication to coupling partner/s
---[precice]  Masters are connected
---[precice]  Setting up preliminary slaves communication to coupling partner/s
---[precice]  Prepare partition for mesh Solid
---[precice]  Gather mesh Solid
---[precice]  Send global mesh Solid
---[precice]  Setting up slaves communication to coupling partner/s
---[precice]  Slaves are connected
ASSERTION FAILED
  Location:          void precice::acceleration::Acceleration::checkDataIDs(const DataMap&) const
  File:              /home/prasad/Downloads/precice/src/acceleration/Acceleration.cpp:12
  Rank:              0
  Failed expression: valid
  Argument 0: Data with ID 2 unknown.
``` 
**Issue**
Benjamin pointed out that I was using `serial-implicit ` coupling scheme, and to use both the data I should actually be using `parallel-implicit`.
The `ASSERTION FAILED ` lead me to think in some other direction and made me think there was some issue with my case.

In `precice-config.xml`, when we are fine tuning the coupling it's easy to miss out on such things. 

**Suggestion**
I think my issue was an easy fix, just by changing from `serial-implicit ` to `parallel-implicit`.
So this may be pointed out in the error message.

P.S: Not really sure what to name the topic, so please feel free to improve it or make suggestions.
Link-up from [discourse](https://precice.discourse.group/t/requesting-better-error-message-for-assertion-failed/338)

**Comment by uekerman** [comment] 2021-01-17 17:35
Duplicate of #907, already solved in #913

**Closed by uekerman** 2021-01-17 17:35 UTC
Labels: bug
