### ISSUE TITLE
issiue in compiling preCICE

### ISSUE THREAD

**Issue by bitronTeofil** [precice/precice#493] opened 2019-08-23 06:23 UTC
[compiling.log](https://github.com/precice/precice/files/3533069/compiling.log)
Was for the last three days I’m trying to compile preCICE, and I found many trouble due to my difficulties in manage Linux environment.

Finally, I was able to solve all the dependencies. In the attached file you could find the complete cmake log (compiling.log).

Now I have the problem about the gcc 4.8 limit in manage the C++ 11 feature. For this reason I installed gcc-5 version 5.3.1. Here is the compiling error:

******-- Found Git: /usr/bin/git (found version "2.13.7") 
-- Revision status: v1.5.2-125-g675a2425
[  0%] Built target GitRevision
[  0%] Building CXX object CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o
/home/alessandro/downloads/fem/preCICE/precice/src/utils/EventUtils.cpp: In function ‘std::string precice::utils::timepoint_to_string(std::chrono::_V2::system_clock::time_point)’:
/home/alessandro/downloads/fem/preCICE/precice/src/utils/EventUtils.cpp:33:9: error: ‘**_put_time_**’ is not a member of ‘std’
   ss << std::put_time(std::localtime(&ts), "%FT%T") << "." << std::setw(3) << std::setfill('0') << ms.count();**
         ^
**CMakeFiles/precice.dir/build.make:1557: set di istruzioni per l'obiettivo "CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o" non riuscito
make[2]: *** [CMakeFiles/precice.dir/src/utils/EventUtils.cpp.o] Errore 1
CMakeFiles/Makefile2:88: set di istruzioni per l'obiettivo "CMakeFiles/precice.dir/all" non riuscito
make[1]: *** [CMakeFiles/precice.dir/all] Errore 2
Makefile:162: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2**

Also in the cmake log file, it seems that preCICE still find the 4.8 version of gcc:

**-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info – done
…
…**

How could I fix it?
Many thanks in advance for your help

**Comment by MakisH** [comment] 2019-08-23 07:07
Duplicate of https://github.com/precice/precice/issues/492.

**Closed by MakisH** 2019-08-23 07:07 UTC
